DELIMITER ;;

CREATE OR REPLACE PROCEDURE BudgetApp.SP_PROCESS_AXIS_REPORTING()
BEGIN
    DECLARE varBankId INT;
    DECLARE varLogId INT;
    DECLARE varRowCount INT DEFAULT 0;

    -- Initialize Log
    SELECT BANK_ID INTO varBankId FROM BudgetApp.BANKS WHERE BANK_NAME LIKE '%Axis%' AND IS_CURRENT = 1 LIMIT 1;
    INSERT INTO BudgetApp.ETL_LOG (PROC_NAME, BANK_ID, STATUS) VALUES ('SP_PROCESS_AXIS_REPORTING', varBankId, 'STARTED');
    SET varLogId = LAST_INSERT_ID();

    -- Error Handling
    BEGIN
        DECLARE EXIT HANDLER FOR SQLEXCEPTION 
        BEGIN
            GET DIAGNOSTICS CONDITION 1 @p1 = RETURNED_SQLSTATE, @p2 = MESSAGE_TEXT;
            ROLLBACK;
            UPDATE BudgetApp.ETL_LOG SET STATUS = 'FAILED', ERROR_MSG = @p2, END_TIME = NOW() WHERE LOG_ID = varLogId;
        END;

        IF varBankId IS NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Axis Bank ID not found in BANKS table.';
        END IF;

        START TRANSACTION;

        REPLACE INTO BudgetApp.TRANSACTION_REPORTING 
        (TRANSACTION_ID, BANK_ID, MEMBER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT, TRANSACTION_TYPE, 
         PAYMENT_CHANNEL, ENTITY_NAME, GEOGRAPHY, ASSOCIATED_BANK)
        SELECT 
            transaction_id, bank_id, member_id, transaction_date, transaction_amount, transaction_type,
            CASE 
                WHEN DESCRIPTION LIKE 'POS/%' THEN 'DEBIT CARD'
                WHEN DESCRIPTION LIKE 'ECOM PUR/%' THEN 'ONLINE PURCHASE'
                WHEN DESCRIPTION LIKE 'UPI/%' THEN 'UPI'
                WHEN DESCRIPTION LIKE 'IMPS/%' THEN 'IMPS'
                WHEN DESCRIPTION LIKE 'ATM-%' THEN 'CASH WITHDRAWAL'
                WHEN DESCRIPTION LIKE 'MOB/%' THEN 'MOBILE BANKING'
                WHEN DESCRIPTION LIKE 'ECS/%' THEN 'AUTOPAY/ECS'
                WHEN DESCRIPTION LIKE 'NBSM/%' THEN 'NET BANKING'
                WHEN DESCRIPTION LIKE 'PUR-REV/%' THEN 'REVERSAL'
                WHEN DESCRIPTION LIKE 'INT ON SB%' OR DESCRIPTION LIKE 'SB:%' OR DESCRIPTION LIKE '%INT.PD:%' THEN 'BANK INTEREST/TAX'
                ELSE 'OTHERS'
            END,
            TRIM(CASE 
                WHEN DESCRIPTION LIKE 'POS/%' OR DESCRIPTION LIKE 'ECOM PUR/%' THEN SUBSTRING_INDEX(SUBSTRING_INDEX(DESCRIPTION, '/', 2), '/', -1)
                WHEN DESCRIPTION LIKE 'UPI/%' OR DESCRIPTION LIKE 'IMPS/%' THEN SUBSTRING_INDEX(SUBSTRING_INDEX(DESCRIPTION, '/', 4), '/', -1)
                WHEN DESCRIPTION LIKE 'MOB/%' THEN SUBSTRING_INDEX(SUBSTRING_INDEX(DESCRIPTION, '/', 3), '/', -1)
                WHEN DESCRIPTION LIKE 'ECS/%' OR DESCRIPTION LIKE 'NBSM/%' THEN SUBSTRING_INDEX(SUBSTRING_INDEX(DESCRIPTION, '/', 3), '/', -1)
                WHEN DESCRIPTION LIKE 'INT ON SB%' OR DESCRIPTION LIKE 'SB:%' OR DESCRIPTION LIKE '%INT.PD:%' THEN 'BANK SYSTEM'
                WHEN DESCRIPTION LIKE 'ATM-%' THEN 'SELF'
                WHEN DESCRIPTION LIKE 'PUR-REV/%' THEN 'REVERSAL'
                ELSE 'UNKNOWN'
            END),
            TRIM(CASE 
                WHEN DESCRIPTION LIKE 'POS/%' OR DESCRIPTION LIKE 'ECOM PUR/%' THEN SUBSTRING_INDEX(SUBSTRING_INDEX(DESCRIPTION, '/', 3), '/', -1)
                WHEN DESCRIPTION LIKE 'ATM-%' THEN SUBSTRING_INDEX(SUBSTRING_INDEX(DESCRIPTION, '/', 3), '/', -1)
                ELSE 'ONLINE/TRANSFER'
            END),
            TRIM(CASE WHEN DESCRIPTION LIKE 'UPI/%' OR DESCRIPTION LIKE 'IMPS/%' THEN SUBSTRING_INDEX(TRIM(BOTH '/' FROM DESCRIPTION), '/', -1) ELSE NULL END)
        FROM BudgetApp.TRANSACTIONS 
        WHERE BANK_ID = varBankId;

        SET varRowCount = ROW_COUNT();
        COMMIT;

        UPDATE BudgetApp.ETL_LOG SET STATUS = 'SUCCESS', ROWS_PROCESSED = varRowCount, END_TIME = NOW() WHERE LOG_ID = varLogId;
    END;
END ;;
DELIMITER ;