DELIMITER ;;

DROP PROCEDURE IF EXISTS BudgetApp.SP_PROCESS_CAPITALONE_REPORTING ;;

CREATE PROCEDURE BudgetApp.SP_PROCESS_CAPITALONE_REPORTING()
BEGIN
    DECLARE varBankId INT;
    DECLARE varLogId INT;
    DECLARE varRowCount INT DEFAULT 0;

    -- Standardize to handle 'CapitalOne' vs 'Capital One'
    SELECT BANK_ID INTO varBankId FROM BudgetApp.BANKS WHERE BANK_NAME LIKE '%CapitalOne%' AND IS_CURRENT = 1 LIMIT 1;
    INSERT INTO BudgetApp.ETL_LOG (PROC_NAME, BANK_ID, STATUS) VALUES ('SP_PROCESS_CAPITALONE_REPORTING', varBankId, 'STARTED');
    SET varLogId = LAST_INSERT_ID();

    BEGIN
        DECLARE EXIT HANDLER FOR SQLEXCEPTION 
        BEGIN
            GET DIAGNOSTICS CONDITION 1 @p1 = RETURNED_SQLSTATE, @p2 = MESSAGE_TEXT;
            ROLLBACK;
            UPDATE BudgetApp.ETL_LOG SET STATUS = 'FAILED', ERROR_MSG = @p2, END_TIME = NOW() WHERE LOG_ID = varLogId;
        END;

        IF varBankId IS NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Capital One Bank ID not found.';
        END IF;

        START TRANSACTION;

        REPLACE INTO BudgetApp.TRANSACTION_REPORTING 
        (TRANSACTION_ID, BANK_ID, CARD_ID, MEMBER_ID, TRANSACTION_DATE, POSTED_DATE, TRANSACTION_AMOUNT, TRANSACTION_TYPE, 
         PAYMENT_CHANNEL, ENTITY_NAME, CATG_NAME, SUB_CATG_NAME, DETAILED_CATEGORY, TRACE_ID)
        SELECT 
            t.transaction_id, t.bank_id, t.card_id, t.member_id, t.transaction_date, t.posted_date, t.transaction_amount, t.transaction_type,
            CASE 
                WHEN t.DESCRIPTION LIKE 'CAPITAL ONE MOBILE PYMT%' THEN 'PAYMENT'
                WHEN msc.SUB_CATG_NAME = 'AIRFARE' OR t.DESCRIPTION LIKE '%AIR%' THEN 'AIRLINE'
                WHEN msc.SUB_CATG_NAME = 'GAS/AUTOMOTIVE' OR t.DESCRIPTION LIKE 'NTTA%' THEN 'TRANSPORT/GAS'
                WHEN t.DESCRIPTION LIKE 'COT*%' THEN 'TRAVEL PORTAL'
                ELSE 'CREDIT CARD'
            END,
            TRIM(CASE
                WHEN t.DESCRIPTION LIKE 'SOUTHWES%' THEN 'SOUTHWEST AIRLINES'
                WHEN t.DESCRIPTION LIKE 'AMERICAN %' THEN 'AMERICAN AIRLINES'
                WHEN t.DESCRIPTION LIKE 'UNITED %' THEN 'UNITED AIRLINES'
                WHEN t.DESCRIPTION LIKE 'ETIHAD %' THEN 'ETIHAD AIRWAYS'
                WHEN t.DESCRIPTION LIKE 'QATAR AIR%' THEN 'QATAR AIRWAYS'
                WHEN t.DESCRIPTION LIKE 'KRISHNA INSTITUTE%' THEN 'KRISHNA INSTITUTE OF MEDICAL SCIENCES'
                WHEN t.DESCRIPTION = 'COT*HTL' THEN 'CAPITAL ONE TRAVEL - HOTEL'
                WHEN t.DESCRIPTION = 'COT*FLT' THEN 'CAPITAL ONE TRAVEL - FLIGHT'
                ELSE TRIM(REGEXP_REPLACE(
                         REPLACE(REPLACE(t.DESCRIPTION, 'TST* ', ''), 'COT*', ''),
                         '[0-9]{10,}.*|[ ]{2,}.*', ''
                     ))
            END),
            mc.CATG_NAME,
            msc.SUB_CATG_NAME,
            UPPER(TRIM(msc.SUB_CATG_NAME)),
            REGEXP_SUBSTR(t.DESCRIPTION, '[0-9]{10,}')
        FROM BudgetApp.TRANSACTIONS t
        LEFT JOIN BudgetApp.MCC_CATEGORY mc ON t.CATG_ID = mc.CATG_ID
        LEFT JOIN BudgetApp.MCC_SUB_CATEGORY msc ON t.SUB_CATG_ID = msc.SUB_CATG_ID AND t.CATG_ID = msc.CATG_ID
        WHERE t.BANK_ID = varBankId;

        SET varRowCount = ROW_COUNT();
        COMMIT;

        UPDATE BudgetApp.ETL_LOG SET STATUS = 'SUCCESS', ROWS_PROCESSED = varRowCount, END_TIME = NOW() WHERE LOG_ID = varLogId;
    END;
END ;;
DELIMITER ;