DELIMITER ;;

CREATE OR REPLACE PROCEDURE BudgetApp.SP_PROCESS_CITI_REPORTING()
BEGIN
    DECLARE varBankId INT;
    DECLARE varLogId INT;
    DECLARE varRowCount INT DEFAULT 0;

    SELECT BANK_ID INTO varBankId FROM BudgetApp.BANKS WHERE BANK_NAME LIKE '%Citi%' AND IS_CURRENT = 1 LIMIT 1;
    INSERT INTO BudgetApp.ETL_LOG (PROC_NAME, BANK_ID, STATUS) VALUES ('SP_PROCESS_CITI_REPORTING', varBankId, 'STARTED');
    SET varLogId = LAST_INSERT_ID();

    BEGIN
        DECLARE EXIT HANDLER FOR SQLEXCEPTION 
        BEGIN
            GET DIAGNOSTICS CONDITION 1 @p1 = RETURNED_SQLSTATE, @p2 = MESSAGE_TEXT;
            ROLLBACK;
            UPDATE BudgetApp.ETL_LOG SET STATUS = 'FAILED', ERROR_MSG = @p2, END_TIME = NOW() WHERE LOG_ID = varLogId;
        END;

        IF varBankId IS NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Citi Bank ID not found.';
        END IF;

        START TRANSACTION;

        REPLACE INTO BudgetApp.TRANSACTION_REPORTING 
        (TRANSACTION_ID, BANK_ID, MEMBER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT, TRANSACTION_TYPE, 
         PAYMENT_CHANNEL, ENTITY_NAME, GEOGRAPHY, DETAILED_CATEGORY)
        SELECT 
            transaction_id, bank_id, member_id, transaction_date, transaction_amount, transaction_type,
            CASE 
                WHEN DESCRIPTION LIKE '%PAYMENT%THANK YOU%' THEN 'PAYMENT'
                WHEN DESCRIPTION LIKE 'WWW %' OR DESCRIPTION LIKE '%.COM%' THEN 'ONLINE PURCHASE'
                WHEN DESCRIPTION LIKE '%GAS %' OR DESCRIPTION REGEXP 'TEXACO|BUC-EE|EXXON|SHELL|CONOCO|QT|7-ELEVEN|LOVE\'S' THEN 'GAS STATION'
                ELSE 'CREDIT CARD'
            END,
            TRIM(CASE 
                WHEN DESCRIPTION LIKE '%PAYMENT%THANK YOU%' THEN 'CITI BANK'
                WHEN DESCRIPTION LIKE 'COSTCO GAS %' THEN 'COSTCO GAS'
                WHEN DESCRIPTION LIKE 'COSTCO WHSE%' THEN 'COSTCO'
                WHEN DESCRIPTION LIKE 'WWW COSTCO COM%' THEN 'COSTCO ONLINE'
                WHEN DESCRIPTION LIKE 'USPS.COM%' THEN 'USPS ONLINE'
                WHEN DESCRIPTION LIKE 'PROGRESSIVE *INSURANCE%' THEN 'PROGRESSIVE'
                ELSE TRIM(REGEXP_REPLACE(
                         REPLACE(REPLACE(REPLACE(REPLACE(DESCRIPTION, 'TST* ', ''), 'PY * ', ''), 'SQ * ', ''), 'SP * ', ''),
                         '([ ]+(#|[0-9]{4,}|[0-9]{2,}-[0-9]+|[A-Z. ]+ [A-Z]{2}$|800-|888-|877-).*)', ''
                     ))
            END),
            TRIM(CASE 
                WHEN DESCRIPTION LIKE '%PAYMENT%THANK YOU%' THEN 'ONLINE'
                WHEN DESCRIPTION REGEXP '[A-Z. ]+ [A-Z]{2}$' THEN REGEXP_SUBSTR(DESCRIPTION, '[A-Z. ]+ [A-Z]{2}$')
                ELSE 'ONLINE/TRANSFER'
            END),
            'MERCHANDISE'
        FROM BudgetApp.TRANSACTIONS 
        WHERE BANK_ID = varBankId;

        SET varRowCount = ROW_COUNT();
        COMMIT;

        UPDATE BudgetApp.ETL_LOG SET STATUS = 'SUCCESS', ROWS_PROCESSED = varRowCount, END_TIME = NOW() WHERE LOG_ID = varLogId;
    END;
END ;;
DELIMITER ;