CREATE TABLE `BANKS` (
  `BANK_ID` int NOT NULL AUTO_INCREMENT,
  `BANK_KEY` int NOT NULL,
  `BANK_NAME` varchar(50) NOT NULL,
  `ACCOUNT_TYPE` varchar(50) NOT NULL,
  `EFF_START_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EFF_END_DATE` datetime NOT NULL DEFAULT '9999-12-31 23:59:59',
  `IS_CURRENT` tinyint(1) NOT NULL DEFAULT '1',
  `ADDED_USER` varchar(20) NOT NULL,
  PRIMARY KEY (`BANK_ID`),
  KEY `idx_bank_key` (`BANK_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
