CREATE TABLE BudgetApp.ETL_LOG (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROC_NAME VARCHAR(100) NOT NULL,
    BANK_ID INT,
    START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    END_TIME TIMESTAMP NULL,
    ROWS_PROCESSED INT DEFAULT 0,
    STATUS VARCHAR(20), -- 'SUCCESS', 'FAILED', 'STARTED'
    ERROR_MSG TEXT,
    INDEX idx_proc (PROC_NAME),
    INDEX idx_start (START_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;