DROP TABLE BudgetApp.EXCHANGE_RATES;


CREATE TABLE BudgetApp.EXCHANGE_RATES (
    RATE_DATE VARCHAR(20) NOT NULL, -- Format: mm/dd/yy
    FROM_CURRENCY VARCHAR(3) NOT NULL DEFAULT 'USD', -- e.g., 'USD'
    TO_CURRENCY VARCHAR(3) NOT NULL DEFAULT 'INR',   -- e.g., 'INR'
    CONVERSION_RATE DECIMAL(10,6) NOT NULL, -- e.g., 83.5500
    PRIMARY KEY (RATE_DATE, FROM_CURRENCY, TO_CURRENCY),
    INDEX idx_rate_lookup (FROM_CURRENCY, TO_CURRENCY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
