DROP TABLE IF EXISTS `LND_TRANSACTIONS`;


CREATE TABLE `LND_TRANSACTIONS` (
  `TRANSACTION_DATE` varchar(30) DEFAULT NULL,
  `POSTED_DATE` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `AMOUNT` varchar(30) DEFAULT NULL,
  `EXT_DETAILS` varchar(1000) DEFAULT NULL,
  `STATEMENT_DESC` varchar(1000) DEFAULT NULL,
  `ADDRESS` varchar(1000) DEFAULT NULL,
  `CITY_STATE` varchar(1000) DEFAULT NULL,
  `ZIPCODE` varchar(50) DEFAULT NULL,
  `COUNTRY` varchar(50) DEFAULT NULL,
  `REFERENCE` varchar(100) DEFAULT NULL,
  `CATEGORY` varchar(1000) DEFAULT NULL,
  `DEBIT` varchar(30) DEFAULT NULL,
  `CREDIT` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
