CREATE TABLE `MCC_SUB_CATEGORY` (
  `SUB_CATG_ID` int NOT NULL AUTO_INCREMENT,
  `SUB_CATG_NAME` varchar(150) NOT NULL,
  `CATG_ID` int NOT NULL,
  `ADDED_USER` varchar(50) NOT NULL,
  `ADDED_DATETIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SUB_CATG_ID`),
  KEY `mcc_sub_category_ibfk_1` (`CATG_ID`),
  CONSTRAINT `mcc_sub_category_ibfk_1` FOREIGN KEY (`CATG_ID`) REFERENCES `MCC_CATEGORY` (`CATG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
