CREATE TABLE `MCC_CATEGORY` (
  `CATG_ID` int NOT NULL AUTO_INCREMENT,
  `CATG_NAME` varchar(150) NOT NULL,
  `ADDED_USER` varchar(50) NOT NULL,
  `ADDED_DATETIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CATG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
