CREATE TABLE `MEMBERS` (
  `MEMBER_ID` int NOT NULL AUTO_INCREMENT,
  `MEMBER_KEY` int NOT NULL,
  `FIRST_NAME` varchar(50) NOT NULL,
  `MIDDLE_NAME` varchar(20) DEFAULT NULL,
  `LAST_NAME` varchar(50) NOT NULL,
  `GENDER` varchar(10) NOT NULL,
  `DATE_OF_BIRTH` varbinary(255) DEFAULT NULL,
  `ADDRESS_ID` int NOT NULL,
  `EFF_START_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EFF_END_DATE` datetime NOT NULL DEFAULT '9999-12-31 23:59:59',
  `IS_CURRENT` tinyint(1) NOT NULL DEFAULT '1',
  `ADDED_USER` varchar(20) NOT NULL,
  PRIMARY KEY (`MEMBER_ID`),
  KEY `idx_member_key` (`MEMBER_KEY`),
  KEY `members_fk_address` (`ADDRESS_ID`),
  CONSTRAINT `members_fk_address` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `MEMBER_ADDRESS` (`ADDRESS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
