CREATE TABLE `MEMBER_ADDRESS` (
  `ADDRESS_ID` int NOT NULL AUTO_INCREMENT,
  `ADDRESS_KEY` int NOT NULL,
  `ADDRESS_1` varchar(150) NOT NULL,
  `ADDRESS_2` varchar(50) DEFAULT NULL,
  `CITY` varchar(50) NOT NULL,
  `STATE` varchar(50) NOT NULL,
  `ZIPCODE` varchar(10) NOT NULL,
  `EFF_START_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EFF_END_DATE` datetime NOT NULL DEFAULT '9999-12-31 23:59:59',
  `IS_CURRENT` tinyint(1) NOT NULL DEFAULT '1',
  `ADDED_USER` varchar(20) NOT NULL,
  PRIMARY KEY (`ADDRESS_ID`),
  KEY `idx_address_key` (`ADDRESS_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
