CREATE TABLE BudgetApp.TRANSACTION_REPORTING (
    TRANSACTION_ID BIGINT NOT NULL,
    BANK_ID INT NOT NULL,
    CARD_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL,
    POSTED_DATE DATETIME,
    TRANSACTION_AMOUNT DECIMAL(19,4) NOT NULL,
    TRANSACTION_TYPE VARCHAR(10) NOT NULL,
    PAYMENT_CHANNEL VARCHAR(50),
    ENTITY_NAME VARCHAR(150),
    GEOGRAPHY VARCHAR(150),
    CATG_NAME VARCHAR(150),
    SUB_CATG_NAME VARCHAR(150),
    DETAILED_CATEGORY VARCHAR(100),
    ASSOCIATED_BANK VARCHAR(100),
    TRACE_ID VARCHAR(100),
    TRANSACTION_MEMO VARCHAR(500),
    INSTALLMENT_PLAN VARCHAR(50),
    LAST_REFRESHED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT fk_reporting_tx_id 
        FOREIGN KEY (TRANSACTION_ID) 
        REFERENCES BudgetApp.TRANSACTIONS (TRANSACTION_ID) 
        ON DELETE CASCADE,
    INDEX idx_rpt_date (TRANSACTION_DATE),
    INDEX idx_rpt_entity (ENTITY_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;