Select * from MEMBER_ADDRESS ma 
;



INSERT INTO BudgetApp.MEMBER_ADDRESS
(ADDRESS_1, ADDRESS_2, CITY, STATE, ZIPCODE, ADDED_USER, ADDED_DATETIME)
VALUES('2911 Central Expy', 'Apt 5204', 'Melissa', 'Texas', '75454', 'DKAKKE',CURRENT_TIMESTAMP);

COMMIT;


ALTER TABLE BudgetApp.MEMBERS MODIFY DATE_OF_BIRTH BLOB;


INSERT INTO BudgetApp.MEMBERS
(FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, ADDRESS_ID, ADDED_USER, ADDED_DATETIME)
VALUES('Dhaman Kumar', '', 'Kakke', 'M', AES_ENCRYPT('1996-05-31', '9849050888'), 1000, 'DKAKKE', CURRENT_TIMESTAMP)
;

COMMIT;

Select * from BudgetApp.MEMBERS;

ALTER TABLE BudgetApp.CARDS MODIFY CARD_NUMBER BLOB;
ALTER TABLE BudgetApp.CARDS MODIFY EXP_DATE BLOB;
ALTER TABLE BudgetApp.CARDS MODIFY CVV BLOB;
ALTER TABLE BudgetApp.CARDS ADD(LAST_4 CHAR(4));

INSERT INTO BudgetApp.BANKS
(BANK_NAME, ACCOUNT_TYPE, ADDED_USER, ADDED_DATETIME)
VALUES('AMEX', 'CREDIT', 'DKAKKE', CURRENT_TIMESTAMP);

COMMIT;

Select * from BudgetApp.BANKS;


INSERT INTO BudgetApp.CARDS
(
	CARD_TYPE, 
	CARD_NUMBER,
	LAST_4, 
	EXP_DATE, 
	CVV, 
	BANK_ID, 
	MEMBER_ID, 
	ADDED_USER, 
	ADDED_DATETIME)
VALUES(
	'CREDIT', 
	AES_ENCRYPT('50271004', '9849050888') , 
	'1004', 
	AES_ENCRYPT('1197', '9849050888') , 
	AES_ENCRYPT('001', '9849050888'), 
	(SELECT BANK_ID FROM BudgetApp.BANKS WHERE BANK_NAME = 'AMEX' LIMIT 1), 
	(SELECT MEMBER_ID FROM BudgetApp.MEMBERS LIMIT 1),
	'DKAKKE', 
	CURRENT_TIMESTAMP
	)
;

COMMIT;

Select * from BudgetApp.MEMBERS;

Select * from CARDS c  ;

Select * from BANKS b ;