SELECT 
	DISTINCT CATEGORY 
FROM TRANSACTIONS
;

SELECT 
	lt.CATEGORY
	,TRIM(SUBSTRING_INDEX(lt.CATEGORY, '-', 1)) AS CATG
	,TRIM(SUBSTRING_INDEX(lt.CATEGORY, '-', -1)) AS SUB_CATG
FROM LND_TRANSACTIONS lt 
;

CREATE TABLE MCC_CATEGORY
(
	CATG_ID INT NOT NULL AUTO_INCREMENT
	,CATG_NAME VARCHAR(150) NOT NULL
	,ADDED_USER VARCHAR(50) NOT NULL
	,ADDED_DATETIME TIMESTAMP NOT NULL
	,PRIMARY KEY (CATG_ID)
);


CREATE TABLE MCC_SUB_CATEGORY
(
	SUB_CATG_ID INT NOT NULL AUTO_INCREMENT
	,SUB_CATG_NAME VARCHAR(150) NOT NULL
	,CATG_ID INT NOT NULL
	,ADDED_USER VARCHAR(50) NOT NULL
	,ADDED_DATETIME TIMESTAMP NOT NULL
	,PRIMARY KEY (SUB_CATG_ID)
	,FOREIGN KEY (CATG_ID) REFERENCES MCC_CATEGORY(CATG_ID)
);



INSERT INTO MCC_CATEGORY
(
	CATG_NAME
	,ADDED_USER
	,ADDED_DATETIME
)
SELECT 
	DISTINCT TRIM(SUBSTRING_INDEX(lt.CATEGORY, '-', 1)) AS CATG
	,'DKAKKE'
	,CURRENT_TIMESTAMP()
FROM LND_TRANSACTIONS lt
WHERE lt.CATEGORY IS NOT NULL
AND TRIM(IFNULL(CATEGORY, '')) != ''
;

COMMIT;

INSERT INTO MCC_CATEGORY
(
	CATG_ID
	,CATG_NAME
	,ADDED_USER
	,ADDED_DATETIME
)
SELECT 
	0
	,'CREDIT TO BANK'
	,'DKAKKE'
	,CURRENT_TIMESTAMP()
;

COMMIT;

SELECT * FROM MCC_CATEGORY;

INSERT INTO MCC_SUB_CATEGORY
(
	SUB_CATG_NAME
	,CATG_ID
	,ADDED_USER
	,ADDED_DATETIME
)
SELECT 
	DISTINCT TRIM(SUBSTRING_INDEX(lt.CATEGORY, '-', -1)) AS CATG
	,MC.CATG_ID
	,'DKAKKE'
	,CURRENT_TIMESTAMP()
FROM LND_TRANSACTIONS lt
JOIN MCC_CATEGORY MC
	ON MC.CATG_NAME = TRIM(SUBSTRING_INDEX(lt.CATEGORY, '-', 1))
WHERE lt.CATEGORY IS NOT NULL
AND TRIM(IFNULL(CATEGORY, '')) != ''
;

COMMIT;

INSERT INTO MCC_SUB_CATEGORY
(
	SUB_CATG_ID
	,SUB_CATG_NAME
	,CATG_ID
	,ADDED_USER
	,ADDED_DATETIME
)
SELECT 
	0
	,'CREDIT T0 BANK'
	,16
	,'DKAKKE'
	,CURRENT_TIMESTAMP()
;

COMMIT;

SELECT * FROM MCC_SUB_CATEGORY;

UPDATE MCC_SUB_CATEGORY
	SET SUB_CATG_NAME = 'CREDIT TO BANK'
WHERE SUB_CATG_ID = 32
;


TRUNCATE TABLE TRANSACTIONS;

COMMIT;


-- BudgetApp.TRANSACTIONS definition
DROP TABLE `TRANSACTIONS` ;


CREATE TABLE `TRANSACTIONS` (
  -- BIGINT is correct for those long Amex IDs
  `TRANSACTION_ID` bigint NOT NULL,
  `TRANSACTION_DATE` datetime NOT NULL,
  `POSTED_DATE` datetime DEFAULT NULL,
  
  -- FIXED: Changed from varchar(3) to varchar(10). 
  -- 'DEBIT' (5) and 'CREDIT' (6) were causing your Truncation Error [1406].
  `TRANSACTION_TYPE` varchar(10) NOT NULL,
  
  `TRANSACTION_AMOUNT` decimal(19,4) NOT NULL,
  `DESCRIPTION` varchar(100) NOT NULL,
  `EXT_DESCRIPTION` varchar(500) DEFAULT NULL,
  `ADDRESS_1` varchar(150) DEFAULT NULL, -- Changed to DEFAULT NULL as Amex data is sometimes missing address
  `ADDRESS_2` varchar(50) DEFAULT NULL,
  `CITY` varchar(50) DEFAULT NULL,       -- Changed to DEFAULT NULL (safe for string splitting failures)
  `STATE` varchar(50) DEFAULT NULL,      -- Changed to DEFAULT NULL
  `COUNTRY` varchar(50) DEFAULT NULL,
  `ZIPCODE` varchar(20) DEFAULT NULL,    -- Increased to 20 for international or extended zip codes
  
  -- Foreign Keys
  `CATG_ID` int NOT NULL,
  `SUB_CATG_ID` int NOT NULL,
  `BANK_ID` int NOT NULL,
  `CARD_ID` int NOT NULL,
  `MEMBER_ID` int NOT NULL,
  
  -- Audit Columns
  `ADDED_USER` varchar(20) NOT NULL,
  `ADDED_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_USER` varchar(20) DEFAULT NULL,
  `UPDATED_DATETIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  
  PRIMARY KEY (`TRANSACTION_ID`),
  
  -- Indexed for performance in your BudgetApp dashboards
  KEY `BANK_ID` (`BANK_ID`),
  KEY `CARD_ID` (`CARD_ID`),
  KEY `MEMBER_ID` (`MEMBER_ID`),
  KEY `CATG_ID` (`CATG_ID`),
  
  -- Standardizing Constraint Names
  CONSTRAINT `fk_transactions_bank` FOREIGN KEY (`BANK_ID`) REFERENCES `BANKS` (`BANK_ID`),
  CONSTRAINT `fk_transactions_card` FOREIGN KEY (`CARD_ID`) REFERENCES `CARDS` (`CARD_ID`),
  CONSTRAINT `fk_transactions_member` FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBERS` (`MEMBER_ID`),
  CONSTRAINT `fk_transactions_catg` FOREIGN KEY (`CATG_ID`) REFERENCES `MCC_CATEGORY` (`CATG_ID`),
  CONSTRAINT `fk_transactions_subcatg` FOREIGN KEY (`SUB_CATG_ID`) REFERENCES `MCC_SUB_CATEGORY` (`SUB_CATG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


SELECT 
        CAST(SUBSTRING(lt.Reference, 2,length(lt.Reference)-1) AS DECIMAL(30,0)) AS TRANSACTION_ID,
        STR_TO_DATE(lt.`Date`, "%m/%d/%Y") AS DT,
        CASE 
            WHEN CAST(lt.Amount AS DECIMAL(30,0)) >= 0 THEN 'DBT'
            ELSE 'CDT'
        END AS TRANSACTION_TYPE,
        CAST(lt.Amount AS DECIMAL(19,4)) AS AMOUNT,
        lt.Description AS DESCRIPTION,
        CONCAT_WS(" ", IFNULL(lt.EXTENDED_DETAILS, ""), "statement:", IFNULL(lt.STATEMENT_DESC, "")) AS EXT_DESCRIPTION,
        lt.ADDRESS,
        NULL,
        TRIM(SUBSTRING(lt.CITY_STATE, 1, LENGTH(lt.CITY_STATE) - 3)) AS CITY,
        TRIM(SUBSTRING(lt.CITY_STATE, LENGTH(lt.CITY_STATE) - 1)) AS STATE,
        lt.COUNTRY,
        lt.ZIPCODE,
        mc.CATG_ID ,
        msc.SUB_CATG_ID, 
        b.BANK_ID,
        c.CARD_ID,
        m.MEMBER_ID,
        'DKAKKE',
        CURRENT_TIMESTAMP()
    FROM LND_TRANSACTIONS lt 
    LEFT JOIN BANKS b 
        ON b.BANK_NAME = 'AMEX'
    LEFT JOIN MEMBERS m 
        ON m.FIRST_NAME = 'Dhaman Kumar'
    LEFT JOIN CARDS c 
        ON c.LAST_4 = '1004'
    LEFT JOIN MCC_CATEGORY mc 
    	ON mc.CATG_NAME = CASE 
	    					WHEN CAST(lt.Amount AS DECIMAL(30,0)) >= 0 THEN TRIM(SUBSTRING_INDEX(lt.CATEGORY, '-', 1)) 
	    					ELSE 'CREDIT TO BANK' 
	    				END
    LEFT JOIN MCC_SUB_CATEGORY msc 
    	ON msc.SUB_CATG_NAME  = CASE 
									WHEN CAST(lt.Amount AS DECIMAL(30,0)) >= 0 THEN TRIM(SUBSTRING_INDEX(lt.CATEGORY, '-', -1)) 
									ELSE 'CREDIT TO BANK' 
							END;


TRUNCATE TABLE TRANSACTIONS;

CALL BudgetApp.Load_Amex_statement(
    'Dhaman Kumar',
    'AMEX',
    '1004'
);


SELECT * FROM TRANSACTIONS;

Select * from LND_TRANSACTIONS lt;







Select 
	DATE_FORMAT(t.TRANSACTION_DATE, '%Y-%m-01')
	,count(*) CNT
	,SUM(TRANSACTION_AMOUNT) SPEND
	,t.catg_id
	,mc.CATG_NAME 
	,t.sub_catg_id
	,msc.SUB_CATG_NAME 
from TRANSACTIONS t 
LEFT JOIN MCC_CATEGORY mc 
	on mc.CATG_ID = t.CATG_ID 
LEFT JOIN MCC_SUB_CATEGORY msc 
	on msc.SUB_CATG_ID = t.sub_catg_id
group by DATE_FORMAT(t.TRANSACTION_DATE, '%Y-%m-01')
	,t.catg_id
	,mc.CATG_NAME 
	,t.sub_catg_id
	,msc.SUB_CATG_NAME 
order by DATE_FORMAT(t.TRANSACTION_DATE, '%Y-%m-01')
	,t.catg_id
	,mc.CATG_NAME 
	,t.sub_catg_id
	,msc.SUB_CATG_NAME 
;



Select 
	DATE_FORMAT(t.TRANSACTION_DATE, '%Y-%m-01')
	,count(*) CNT
	,SUM(TRANSACTION_AMOUNT) SPEND
	,t.catg_id
	,mc.CATG_NAME 
	,t.sub_catg_id
	,msc.SUB_CATG_NAME 
from TRANSACTIONS t 
LEFT JOIN MCC_CATEGORY mc 
	on mc.CATG_ID = t.CATG_ID 
 LEFT JOIN MCC_SUB_CATEGORY msc 
	on msc.SUB_CATG_ID = t.sub_catg_id
group by DATE_FORMAT(t.TRANSACTION_DATE, '%Y-%m-01')
	,t.catg_id
	,mc.CATG_NAME 
	,t.sub_catg_id
	,msc.SUB_CATG_NAME 
order by DATE_FORMAT(t.TRANSACTION_DATE, '%Y-%m-01')
	,t.catg_id
	,mc.CATG_NAME 
--	,t.sub_catg_id
--	,msc.SUB_CATG_NAME 
;



-- BudgetApp.LND_TRANSACTIONS definition
DROP TABLE  `LND_TRANSACTIONS`;


CREATE TABLE `LND_TRANSACTIONS` (
  `TRANSACTION_Date` varchar(30) DEFAULT NULL,
  `POSTED_DATE` varchar(20) DEFAULT NULL,
  `Description` varchar(500) DEFAULT NULL,
  `Amount` varchar(30) DEFAULT NULL,
  `Extended_Details` varchar(500) DEFAULT NULL,
  `Statement_Desc` varchar(500) DEFAULT NULL,
  `Address` varchar(500) DEFAULT NULL,
  `City_State` varchar(500) DEFAULT NULL,
  `ZipCode` varchar(50) DEFAULT NULL,
  `Country` varchar(50) DEFAULT NULL,
  `Reference` varchar(50) DEFAULT NULL,
  `Category` varchar(500) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



-- BudgetApp.MCC_SUB_CATEGORY definition
DROP TABLE `MCC_SUB_CATEGORY` ;

SELECT * FROM MCC_SUB_CATEGORY;

CREATE TABLE `MCC_SUB_CATEGORY` (
  `SUB_CATG_ID` int NOT NULL AUTO_INCREMENT,
  `SUB_CATG_NAME` varchar(150) NOT NULL,
  `CATG_ID` int NOT NULL,
  BANK_ID INT NOT NULL,
  `ADDED_USER` varchar(50) NOT NULL,
  `ADDED_DATETIME` timestamp NOT NULL,
  PRIMARY KEY (`SUB_CATG_ID`),
  KEY `CATG_ID` (`CATG_ID`),
  CONSTRAINT `mcc_sub_category_ibfk_1` FOREIGN KEY (`CATG_ID`) REFERENCES `MCC_CATEGORY` (`CATG_ID`),
  FOREIGN KEY (BANK_ID) REFERENCES BANKS(BANK_ID)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- BudgetApp.MCC_CATEGORY definition

DROP TABLE `MCC_CATEGORY`;

CREATE TABLE `MCC_CATEGORY` (
  `CATG_ID` int NOT NULL AUTO_INCREMENT,
  `CATG_NAME` varchar(150) NOT NULL,
  BANK_ID INT NOT NULL,
  `ADDED_USER` varchar(50) NOT NULL,
  `ADDED_DATETIME` timestamp NOT NULL,
  PRIMARY KEY (`CATG_ID`),
  FOREIGN KEY (BANK_ID) REFERENCES BANKS(BANK_ID)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
