-- 1. Detailed Transaction Log
-- This query joins transactions with members, banks, and cards to provide a human-readable statement.
SELECT 
    t.TRANSACTION_DATE, 
    m.FIRST_NAME, 
    m.LAST_NAME, 
    b.BANK_NAME, 
    c.LAST_4,
    t.DESCRIPTION, 
    t.TRANSACTION_AMOUNT, 
    t.TRANSACTION_TYPE
FROM BudgetApp.TRANSACTIONS t
JOIN BudgetApp.MEMBERS m ON t.MEMBER_ID = m.MEMBER_ID
JOIN BudgetApp.BANKS b ON t.BANK_ID = b.BANK_ID
JOIN BudgetApp.CARDS c ON t.CARD_ID = c.CARD_ID
ORDER BY t.TRANSACTION_DATE DESC;

-- 2. Spending Summary by Category
-- Calculates the total debit amount for each category and sub-category.
SELECT 
    mc.CATG_NAME, 
    msc.SUB_CATG_NAME, 
    SUM(t.TRANSACTION_AMOUNT) AS TOTAL_SPENT
FROM BudgetApp.TRANSACTIONS t
JOIN BudgetApp.MCC_CATEGORY mc ON t.CATG_ID = mc.CATG_ID
JOIN BudgetApp.MCC_SUB_CATEGORY msc ON t.SUB_CATG_ID = msc.SUB_CATG_ID
WHERE t.TRANSACTION_TYPE = 'DBT'
GROUP BY mc.CATG_NAME, msc.SUB_CATG_NAME
ORDER BY TOTAL_SPENT DESC;

-- 3. Active Members and Addresses
-- Lists current members and their current primary addresses (SCD Type 2).
SELECT m.FIRST_NAME, m.LAST_NAME, ma.ADDRESS_1, ma.CITY, ma.STATE, ma.ZIPCODE
FROM BudgetApp.MEMBERS m
JOIN BudgetApp.MEMBER_ADDRESS ma ON m.ADDRESS_ID = ma.ADDRESS_ID
WHERE m.IS_CURRENT = 1 AND ma.IS_CURRENT = 1;

-- 4. Monthly Financial Health Summary
-- This query provides Income, Spend, and Savings logic.
CREATE OR REPLACE VIEW BudgetApp.VW_MONTHLY_SUMMARY AS
SELECT 
    DATE_FORMAT(TRANSACTION_DATE, '%Y-%m') AS MONTH,
    SUM(CASE WHEN TRANSACTION_TYPE = 'CRD' THEN TRANSACTION_AMOUNT ELSE 0 END) AS TOTAL_INCOME,
    SUM(CASE WHEN TRANSACTION_TYPE = 'DBT' THEN TRANSACTION_AMOUNT ELSE 0 END) AS TOTAL_SPEND,
    SUM(CASE WHEN TRANSACTION_TYPE = 'CRD' THEN TRANSACTION_AMOUNT ELSE 0 END) - 
    SUM(CASE WHEN TRANSACTION_TYPE = 'DBT' THEN TRANSACTION_AMOUNT ELSE 0 END) AS NET_SAVINGS,
    -- Example threshold for overspending (e.g., if spend > 80% of income)
    CASE 
        WHEN SUM(CASE WHEN TRANSACTION_TYPE = 'DBT' THEN TRANSACTION_AMOUNT ELSE 0 END) > 
             SUM(CASE WHEN TRANSACTION_TYPE = 'CRD' THEN TRANSACTION_AMOUNT ELSE 0 END) * 0.8 
        THEN 'OVERSPENT' 
        ELSE 'WITHIN BUDGET' 
    END AS BUDGET_STATUS
FROM BudgetApp.TRANSACTIONS
GROUP BY DATE_FORMAT(TRANSACTION_DATE, '%Y-%m');

-- 5. Spend by Channel and Entity (Parsed from descriptions)
SELECT 
    CASE 
        WHEN DESCRIPTION LIKE 'POS/%' THEN 'DEBIT CARD'
        WHEN DESCRIPTION LIKE 'UPI/%' THEN 'UPI'
        WHEN DESCRIPTION LIKE 'IMPS/%' THEN 'IMPS'
        WHEN DESCRIPTION LIKE 'ATM-%' THEN 'CASH'
        ELSE 'OTHERS'
    END AS CHANNEL,
    TRIM(CASE 
        WHEN DESCRIPTION LIKE 'POS/%' THEN SUBSTRING_INDEX(SUBSTRING_INDEX(DESCRIPTION, '/', 2), '/', -1)
        WHEN DESCRIPTION LIKE 'UPI/%' OR DESCRIPTION LIKE 'IMPS/%' THEN SUBSTRING_INDEX(SUBSTRING_INDEX(DESCRIPTION, '/', 4), '/', -1)
        ELSE 'GENERAL'
    END) AS MERCHANT,
    SUM(TRANSACTION_AMOUNT) AS TOTAL_AMOUNT
FROM BudgetApp.TRANSACTIONS
WHERE TRANSACTION_TYPE = 'DBT'
GROUP BY CHANNEL, MERCHANT
ORDER BY TOTAL_AMOUNT DESC;